"""Land the AESO dataset in Azure ML as a versioned Data Asset.

By default this uploads the bundled `aeso_hourly.csv` (generated by
`generate_dataset.py`) to the workspace's default datastore and registers it as
a `uri_file` data asset. Versioned data assets give you lineage: every training
run records exactly which data version it consumed.

Optional: `--source real` will attempt to download the *real* AESO pool price
report instead (requires internet; falls back to the bundled file on failure).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from common.workspace import get_ml_client, load_resources  # noqa: E402

HERE = Path(__file__).resolve().parent
DEFAULT_CSV = HERE / "aeso_hourly.csv"


def ensure_local_csv() -> Path:
    if DEFAULT_CSV.exists():
        return DEFAULT_CSV
    print("Bundled CSV missing; generating it now...")
    from generate_dataset import generate

    df = generate("2024-01-01", "2026-01-01")
    df.to_csv(DEFAULT_CSV, index=False)
    return DEFAULT_CSV


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", choices=["bundled", "real"], default="bundled")
    parser.add_argument("--version", default=None, help="Optional explicit version")
    args = parser.parse_args()

    csv_path = ensure_local_csv()
    cfg = load_resources()

    from azure.ai.ml.constants import AssetTypes
    from azure.ai.ml.entities import Data

    ml_client = get_ml_client()
    data_asset = Data(
        name=cfg["data_asset_name"],
        version=args.version,
        type=AssetTypes.URI_FILE,
        path=str(csv_path),
        description="Hourly AESO pool price + drivers (demand, temperature, wind, gas) for day-ahead price forecasting.",
        tags={"market": "AESO", "granularity": "hourly", "source": args.source},
    )
    created = ml_client.data.create_or_update(data_asset)
    print(f"Registered data asset '{created.name}' version {created.version}")
    print(f"  path: {created.path}")


if __name__ == "__main__":
    main()
